require("snacks").setup ({
    animate = { enabled = false },
	bigfile = { enabled = false },
    dashboard = { enabled = false },
    dim = { enabled = false },
    explorer = { enabled = false, replace_netrw = false },
    image = { enabled = false },
    indent = { enabled = false },
    input = { enabled = true },
    layout = { enabled = false },
    notifier = { enabled = false },
    quickfile = { enabled = false },
    scope = { enabled = false },
    scratch = { enabled = false },
    scroll = { enabled = false },
    statuscolumn = { enabled = true },
    terminal = { enabled = false },
    toggle = { enabled = false },
    words = { enabled = false },
    zen = { enabled = false },
    picker = {
        sources = {
            files = {
                hidden = true,
                ignored = true,
                win = {
                    input = {
                        keys = {
                            ["<S-h>"] = "toggle_hidden",
                            ["<S-i>"] = "toggle_ignored",
                            ["<S-f>"] = "toggle_follow",
                            ["<C-y>"] = { "yazi_copy_relative_path", mode = { "n", "i" } },
                        },
                    },
                },
                exclude = {
                    "**/.git/*",
                    "**/node_modules/*",
                    "**/.yarn/cache/*",
                    "**/.yarn/install*",
                    "**/.yarn/releases/*",
                    "**/.pnpm-store/*",
                    "**/.idea/*",
                    "**/.DS_Store",
                    "build/*",
                    "coverage/*",
                    "dist/*",
                    "hodor-types/*",
                    "**/target/*",
                    "**/public/*",
                    "**/digest*.txt",
                    "**/.node-gyp/**",
                },
            },
            grep = {
                hidden = true,
                ignored = true,
                win = {
                    input = {
                        keys = {
                            ["<S-h>"] = "toggle_hidden",
                            ["<S-i>"] = "toggle_ignored",
                            ["<S-f>"] = "toggle_follow",
                        },
                    },
                },
                exclude = {
                    "**/.git/*",
                    "**/node_modules/*",
                    "**/.yarn/cache/*",
                    "**/.yarn/install*",
                    "**/.yarn/releases/*",
                    "**/.pnpm-store/*",
                    "**/.venv/*",
                    "**/.idea/*",
                    "**/.DS_Store",
                    "**/yarn.lock",
                    "build*/*",
                    "coverage/*",
                    "dist/*",
                    "certificates/*",
                    "hodor-types/*",
                    "**/target/*",
                    "**/public/*",
                    "**/digest*.txt",
                    "**/.node-gyp/**",
                },
            },
            grep_buffers = {},
            explorer = {
                hidden = true,
                ignored = true,
                supports_live = true,
                auto_close = true,
                diagnostics = true,
                diagnostics_open = false,
                focus = "list",
                follow_file = true,
                git_status = true,
                git_status_open = false,
                git_untracked = true,
                jump = { close = true },
                tree = true,
                watch = true,
                exclude = {
                    ".git",
                    ".pnpm-store",
                    ".venv",
                    ".DS_Store",
                    "**/.node-gyp/**",
                },
            },
        },
    },
})
